import type { Config } from "tailwindcss";
import { Theme } from "./lib/theme";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Semantic colors from Theme.colors
        primary: {
          DEFAULT: Theme.colors.primary,
          80: Theme.colors.primary80,
          50: Theme.colors.primary50,
          30: Theme.colors.primary30,
          light: Theme.colors.primaryLight,
        },
        secondary: {
          DEFAULT: Theme.colors.secondary,
          80: Theme.colors.secondary80,
          50: Theme.colors.secondary50,
          30: Theme.colors.secondary30,
          lighter: Theme.colors.secondaryLighter,
          light: Theme.colors.secondaryLight,
          medium: Theme.colors.secondaryMedium,
        },
        error: Theme.colors.error,
        background: {
          DEFAULT: Theme.colors.background,
          light: Theme.colors.primaryLight,
        },
        text: {
          DEFAULT: Theme.colors.text,
          label: Theme.colors.label,
          placeholder: Theme.colors.inputPlaceholder,
        },
        border: {
          light: Theme.colors.lightBorder,
          line: Theme.colors.lightLine,
          grey: Theme.brand.borderGrey,
        },
        // Brand colors
        brand: {
          black: Theme.brand.black,
          white: Theme.brand.white,
          flashWhite: Theme.brand.flashWhite,
          grey: Theme.brand.grey,
          line: Theme.brand.line,
          coolGrey: Theme.brand.coolGrey,
          coolBlue: Theme.brand.coolBlue,
          highlightGrey: Theme.brand.highlightGrey,
          green: Theme.brand.green,
          emeraldGreen: Theme.brand.emeraldGreen,
          eventBlue: Theme.brand.eventBlue,
          purple: {
            50: Theme.brand.purple[50],
            100: Theme.brand.purple[100],
            200: Theme.brand.purple[200],
            300: Theme.brand.purple[300],
            500: Theme.brand.purple[500],
            900: Theme.brand.purple[900],
          },
          purple02: Theme.brand.purple02,
          red: Theme.brand.red,
          lightYellow: Theme.brand.lightYellow,
          goldenStar: Theme.brand.goldenStar,
          yellow: Theme.brand.yellow,
          darkYellow: Theme.brand.darkYellow,
          orange: Theme.brand.orange,
          lightGrey: Theme.brand.lightGrey,
          raspberryPink: Theme.brand.raspberryPink,
          coralOrange: Theme.brand.coralOrange,
          tealGreen: Theme.brand.tealGreen,
          limeGreen: Theme.brand.limeGreen,
          periwinkleBlue: Theme.brand.periwinkleBlue,
          redSalsa: Theme.brand.redSalsa,
          sunflowerYellow: Theme.brand.sunflowerYellow,
          amber: Theme.brand.amber,
          mediumGreen: Theme.brand.mediumGreen,
          deepCyan: Theme.brand.deepCyan,
          paleCornflowerBlue: Theme.brand.paleCornflowerBlue,
          amethystPurple: Theme.brand.amethystPurple,
          rosePink: Theme.brand.rosePink,
          charcoalBlue: Theme.brand.charcoalBlue,
          darkGray: Theme.brand.darkGray,
          darkGrey400: Theme.brand.darkGrey400,
          lightGreen: Theme.brand.lightGreen,
          pink: Theme.brand.pink,
          thistle: Theme.brand.thistle,
          buttercup: Theme.brand.buttercup,
          greenGradient: Theme.brand.greenGradient,
          ghostWhite: Theme.brand.ghostWhite,
          defaultNoteBackground: Theme.brand.defaultNoteBackground,
          borderGrey: Theme.brand.borderGrey,
          lightTealCyan: Theme.brand.lightTealCyan,
          lightLavenderBlue: Theme.brand.lightLavenderBlue,
          lightCreamYellow: Theme.brand.lightCreamYellow,
          lightMintGreen: Theme.brand.lightMintGreen,
          lightLavenderPink: Theme.brand.lightLavenderPink,
          lightLavenderPurple: Theme.brand.lightLavenderPurple,
          lightSkyBlue: Theme.brand.lightSkyBlue,
          lightGreyBlue: Theme.brand.lightGreyBlue,
          lightPeach: Theme.brand.lightPeach,
          lightBlueGrey: Theme.brand.lightBlueGrey,
          lightRosePink: Theme.brand.lightRosePink,
          lavender: Theme.brand.lavender,
          periwinkleBlueStroke: Theme.brand.periwinkleBlueStroke,
          goldenSunburst: Theme.brand.goldenSunburst,
          mintGreen: Theme.brand.mintGreen,
          orchidPurple: Theme.brand.orchidPurple,
          royalLavender: Theme.brand.royalLavender,
          brightAzure: Theme.brand.brightAzure,
          mistySteel: Theme.brand.mistySteel,
          amberOrange: Theme.brand.amberOrange,
          slateGray: Theme.brand.slateGray,
          blossomPink: Theme.brand.blossomPink,
        },
        // Additional semantic colors
        gold: Theme.colors.gold,
        goldLight: Theme.colors.goldLight,
        darkBlue: Theme.colors.darkBlue,
        greyLight: Theme.colors.greyLight,
        link: Theme.colors.link,
        shadow: Theme.colors.shadow,
      },
      spacing: {
        // 4px base unit spacing scale
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        20: '80px',
        24: '96px',
        32: '128px',
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        full: '999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
        md: '0 2px 4px rgba(0, 0, 0, 0.1)',
        lg: '0 4px 8px rgba(0, 0, 0, 0.15)',
        xl: '0 8px 16px rgba(0, 0, 0, 0.2)',
        custom: '0 0 0 1px rgba(224, 227, 235, 0.16)',
      },
      zIndex: {
        0: '0',
        10: '10',
        20: '20',
        30: '30',
        40: '40',
        50: '50',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        // Typography system
        'h1': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'h2': ['26px', { lineHeight: '30px', fontWeight: '700' }],
        'h3': ['24px', { lineHeight: '28px', fontWeight: '600' }],
        'h4': ['18px', { lineHeight: '22px', fontWeight: '600' }],
        'h5': ['16px', { lineHeight: '20px', fontWeight: '600' }],
        'subheading': ['14.5px', { lineHeight: '18px', fontWeight: '500' }],
        'body': ['14.5px', { lineHeight: '18px', fontWeight: '400' }],
        'bodyBold': ['14.5px', { lineHeight: '18px', fontWeight: '700' }],
        'caption': ['12.5px', { lineHeight: '16px', fontWeight: '400' }],
        'link': ['12.5px', { fontWeight: '500' }],
        'label': ['12px', { fontWeight: '500' }],
        'error': ['12.5px', { lineHeight: '16px', fontWeight: '400' }],
        'small': ['12.5px', { fontWeight: '500' }],
        'medium': ['14px', { fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;

